CREATE TABLE IF NOT EXISTS Thread (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstUser INT,
    secondUser INT,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ChatMessage (
    id INT AUTO_INCREMENT PRIMARY KEY,
    thread INT,
    chatmsg TEXT,
    inputTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
